apiVersion: v1
kind: Secret
metadata:
  name: edu-secrets
  namespace: smart-edu-dev
type: Opaque
stringData:
  DB_PASS: "edu_app_2026"
  REDIS_PASS: ""
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  JWT_PRIVATE_KEY_PATH: "/etc/edu/jwt/private.pem"
  JWT_PUBLIC_KEY_PATH: "/etc/edu/jwt/public.pem"
  WECHAT_APP_ID: "REPLACE_ME"
  WECHAT_APP_SECRET: "REPLACE_ME"
