server:
  port: 8089

spring:
  application:
    name: edu-file
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:100.84.68.115:18848}
        namespace: ${NACOS_NAMESPACE:dev}
      config:
        server-addr: ${NACOS_ADDR:100.84.68.115:18848}
        namespace: ${NACOS_NAMESPACE:dev}
        file-extension: yaml

logging:
  level:
    cn.smu.edu: INFO
