export { http, setAccessToken } from './client'
export { authApi } from './modules/auth'
export { userApi } from './modules/user'
export { courseApi, materialApi, useCourseList, useMyClasses, useLessonDetail, useActiveLesson, useStartLesson, useEndLesson, useMaterialList } from './modules/course'
export { interactionApi, useCurrentCode, useGenerateCode, useAttend, useAttendanceList, useRollCall } from './modules/interaction'
export type { TokenVO, SmsLoginDTO } from './modules/auth'
export type { UserVO, UserQueryParams, PageResult, DeptTreeNode, RoleVO } from './modules/user'
export type { CourseListItemVO, ClassRoomVO, LessonDetailVO, LessonStartVO, LessonEndVO, MaterialListItemVO, MaterialUploadVO, MaterialCompleteVO, ApiPageResult } from './modules/course'
export type { AttendCodeVO, AttendResultVO, AttendanceItemVO, AttendanceListVO, BarrageDTO, RollCallDTO, RollCallVO, SlideFeedbackDTO, ClassScoreDTO } from './modules/interaction'
export { examApi, examStudentApi, examPublishApi, useQuestionBanks, useQuestions, useCreateBank, useCreateQuestion, useDeleteQuestion, QUESTION_TYPES, OPTION_TYPES, useExamPapers, usePaperDetail, useCreatePaper, useDeletePaper, useAddQuestionsToPaper, useRemovePaperQuestion } from './modules/exam'
export type { QuestionBankVO, QuestionVO, QuestionOptionVO, QuestionCreateDTO, QuestionOptionDTO, QuestionBankCreateDTO, ExamPaperVO, ExamPaperDetailVO, PaperQuestionVO, ExamPaperCreateDTO, ExamPaperQueryParams, AddQuestionDTO, ExamEnterVO, ExamEnterDTO, ExamQuestionPageVO, PaperQuestionDetailVO, AnswerItemDTO, SubmitAnswerDTO, SubmitResultVO, HeartbeatVO, ExamPublishVO, StudentExamListVO, ExamPublishQueryParams, FaceVerifyResultVO, StudentAnswerVO, ExamScoreSummaryVO, ExamPublishCreateDTO } from './modules/exam'
export { aiApi, useAiReviewResults, useTriggerAiReview, useOverrideReview, mindmapApi, useMindmap, useRegenerateMindmap, useSetMindmapVisible, useSaveMindmapContent, dialogueApi, streamDialogueMessage, useCreateDialogue, useDialogueHistory, useLessonDialogues, questionGenApi, useStartQuestionGen, useQuestionGenStatus, useGeneratedQuestions } from './modules/ai'
export type { AiReviewResultVO, TeacherReviewDTO, MindmapNode, MindmapVO, DialogueTaskDTO, DialogueTaskVO, DialogueMessageVO, DialogueSessionSummaryVO, DialogueStreamHandlers, QuestionGenerateDTO, QuestionTaskVO, GeneratedQuestionVO } from './modules/ai'
export { statApi, useRealtimeOverview, useDeptHistory, useClassHistory, useDeptRanking, STAT_REFRESH_MS } from './modules/stat'
export type { RealtimeOverviewVO, DeptPeriodStatVO, DeptHistoryVO, ClassDailyStatVO, ClassHistoryVO, DeptRankItem } from './modules/stat'
