server:
  port: 18082

spring:
  application:
    name: edu-user
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:100.84.68.115:18848}
        namespace: ${NACOS_NAMESPACE:dev}
      config:
        server-addr: ${NACOS_ADDR:100.84.68.115:18848}
        namespace: ${NACOS_NAMESPACE:dev}
        file-extension: yaml
  datasource:
    url: jdbc:mysql://${DB_HOST:100.84.68.115}:${DB_PORT:13306}/edu_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:edu_app}
    password: ${DB_PASS:edu_app_2026}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    cn.smu.edu: INFO
    cn.smu.edu.user.repository: DEBUG
